# Generated by Django 3.2.7 on 2021-11-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockapi',
            name='api_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
