[http]
# Default URI (will be used if `URI` in case.xlsx was empty)
URI = http://
# Default port (will be used if `Port` in case.xlsx was empty)
Port =
#Default Content-Type (the same)
content_type = application/x-www-form-urlencoded;charset=UTF-8

[shell]
#ssh info
ssh_hostname=
ssh_username=
ssh_password=

[case]
#TestCase file path
filepath = case/case.xlsx

#TestCase sheet names
sheets = ['test']


[database]
#Oracle Connection
driver=oracle.jdbc.driver.OracleDriver
#url=jdbc:oracle:thin:@localhost:1521:orcl
url=
user=
password=













