[http]
# Default interface URI, if `URI` in case.xlsx was empty, this will be used
URI = http://x
# Port information, if `Port` in case.xlsx was empty, this will be used
Port = x
#Content-Type information
content_type = application/x-www-form-urlencoded;charset=UTF-8

[shell]
#ssh info
ssh_hostname=x
ssh_username=x
ssh_password=x

[case]
#TestCase file path
#windows system:
filepath = data/CMB-IRS-AUTOTEST-CASE.xlsx
#linux system:
#filepath = data/interfacedate-new.xls

#TestCase sheet names
sheets = ['x']




[database]
#SUPPORT ORACLE ONLY
#read https://cx-oracle.readthedocs.io/en/latest/user_guide/installation.html#wininstall
#if you don't know what is 'oracle instant client'
db_oracle_lib_dir=C:\oracle\instantclient_19_11
db_uri=x
db_username=x
db_password=x













